create table public.routes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  distance_km double precision not null,
  elevation_gain_m double precision not null,
  start_altitude_m double precision not null,
  end_altitude_m double precision not null,
  avg_grade_percent double precision not null,
  max_grade_percent double precision not null,
  created_at timestamptz not null default now(),
  original_image_path text
);

create table public.route_segments (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.routes(id) on delete cascade,
  start_km double precision not null,
  end_km double precision not null,
  grade_percent double precision not null,
  start_altitude_m double precision not null,
  end_altitude_m double precision not null
);

create table public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  route_id bigint not null references public.routes(id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  status text not null check (status in ('completed', 'partial')),
  active_seconds integer not null,
  total_seconds integer not null,
  distance_km double precision not null,
  avg_power_w integer not null,
  max_power_w integer not null,
  avg_cadence_rpm integer not null,
  avg_speed_kph double precision not null,
  completed_elevation_m double precision not null
);

create table public.activity_samples (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  timestamp_ms bigint not null,
  elapsed_seconds integer not null,
  km double precision not null,
  speed_kph double precision not null,
  cadence_rpm integer not null,
  power_w integer not null,
  grade_percent double precision not null,
  altitude_m double precision not null,
  paused boolean not null
);

create table public.user_settings (
  user_id uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  openai_api_key_encrypted text,
  max_trainer_grade_percent double precision not null default 16,
  enable_negative_grades boolean not null default true,
  smooth_grade_changes boolean not null default true,
  rider_weight_kg double precision not null default 75,
  bike_weight_kg double precision not null default 9,
  updated_at timestamptz not null default now()
);

create table public.imported_images (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  path text not null,
  created_at timestamptz not null default now()
);

create index routes_user_created_idx on public.routes (user_id, created_at desc);
create index route_segments_route_idx on public.route_segments (route_id, start_km);
create index activities_user_started_idx on public.activities (user_id, started_at desc);
create index activities_route_idx on public.activities (route_id);
create index activity_samples_activity_idx on public.activity_samples (activity_id, elapsed_seconds);
create index imported_images_user_idx on public.imported_images (user_id);

alter table public.routes enable row level security;
alter table public.route_segments enable row level security;
alter table public.activities enable row level security;
alter table public.activity_samples enable row level security;
alter table public.user_settings enable row level security;
alter table public.imported_images enable row level security;

create policy routes_owner_all on public.routes
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy route_segments_owner_all on public.route_segments
  for all to authenticated
  using (exists (
    select 1 from public.routes
    where routes.id = route_segments.route_id
      and routes.user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.routes
    where routes.id = route_segments.route_id
      and routes.user_id = (select auth.uid())
  ));

create policy activities_owner_all on public.activities
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.routes
      where routes.id = activities.route_id
        and routes.user_id = (select auth.uid())
    )
  );

create policy activity_samples_owner_all on public.activity_samples
  for all to authenticated
  using (exists (
    select 1 from public.activities
    where activities.id = activity_samples.activity_id
      and activities.user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.activities
    where activities.id = activity_samples.activity_id
      and activities.user_id = (select auth.uid())
  ));

create policy user_settings_owner_all on public.user_settings
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy imported_images_owner_all on public.imported_images
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create or replace function public.create_route(draft jsonb)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  new_route_id bigint;
  segment jsonb;
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  insert into public.routes (
    user_id, name, distance_km, elevation_gain_m, start_altitude_m,
    end_altitude_m, avg_grade_percent, max_grade_percent, original_image_path
  ) values (
    auth.uid(),
    draft->>'name',
    (draft->>'distance_km')::double precision,
    (draft->>'elevation_gain_m')::double precision,
    (draft->>'start_altitude_m')::double precision,
    (draft->>'end_altitude_m')::double precision,
    (draft->>'avg_grade_percent')::double precision,
    (draft->>'max_grade_percent')::double precision,
    nullif(draft->>'original_image_path', '')
  )
  returning id into new_route_id;

  for segment in select value from jsonb_array_elements(draft->'segments')
  loop
    insert into public.route_segments (
      route_id, start_km, end_km, grade_percent, start_altitude_m, end_altitude_m
    ) values (
      new_route_id,
      (segment->>'start_km')::double precision,
      (segment->>'end_km')::double precision,
      (segment->>'grade_percent')::double precision,
      (segment->>'start_altitude_m')::double precision,
      (segment->>'end_altitude_m')::double precision
    );
  end loop;

  return new_route_id;
end;
$$;

create or replace function public.update_route(target_route_id bigint, draft jsonb)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  segment jsonb;
begin
  update public.routes set
    name = draft->>'name',
    distance_km = (draft->>'distance_km')::double precision,
    elevation_gain_m = (draft->>'elevation_gain_m')::double precision,
    start_altitude_m = (draft->>'start_altitude_m')::double precision,
    end_altitude_m = (draft->>'end_altitude_m')::double precision,
    avg_grade_percent = (draft->>'avg_grade_percent')::double precision,
    max_grade_percent = (draft->>'max_grade_percent')::double precision,
    original_image_path = nullif(draft->>'original_image_path', '')
  where id = target_route_id and user_id = auth.uid();

  if not found then
    return false;
  end if;

  delete from public.route_segments where route_id = target_route_id;
  for segment in select value from jsonb_array_elements(draft->'segments')
  loop
    insert into public.route_segments (
      route_id, start_km, end_km, grade_percent, start_altitude_m, end_altitude_m
    ) values (
      target_route_id,
      (segment->>'start_km')::double precision,
      (segment->>'end_km')::double precision,
      (segment->>'grade_percent')::double precision,
      (segment->>'start_altitude_m')::double precision,
      (segment->>'end_altitude_m')::double precision
    );
  end loop;
  return true;
end;
$$;

create or replace function public.duplicate_route(target_route_id bigint)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  source_route public.routes%rowtype;
  new_route_id bigint;
begin
  select * into source_route
  from public.routes
  where id = target_route_id and user_id = auth.uid();

  if not found then
    return null;
  end if;

  insert into public.routes (
    user_id, name, distance_km, elevation_gain_m, start_altitude_m,
    end_altitude_m, avg_grade_percent, max_grade_percent, original_image_path
  ) values (
    auth.uid(), source_route.name || ' copia', source_route.distance_km,
    source_route.elevation_gain_m, source_route.start_altitude_m,
    source_route.end_altitude_m, source_route.avg_grade_percent,
    source_route.max_grade_percent, source_route.original_image_path
  ) returning id into new_route_id;

  insert into public.route_segments (
    route_id, start_km, end_km, grade_percent, start_altitude_m, end_altitude_m
  )
  select new_route_id, start_km, end_km, grade_percent, start_altitude_m, end_altitude_m
  from public.route_segments
  where route_id = target_route_id;

  return new_route_id;
end;
$$;

create or replace function public.create_activity(draft jsonb)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  new_activity_id bigint;
  sample jsonb;
begin
  insert into public.activities (
    user_id, route_id, started_at, ended_at, status, active_seconds,
    total_seconds, distance_km, avg_power_w, max_power_w, avg_cadence_rpm,
    avg_speed_kph, completed_elevation_m
  ) values (
    auth.uid(),
    (draft->>'route_id')::bigint,
    (draft->>'started_at')::timestamptz,
    (draft->>'ended_at')::timestamptz,
    draft->>'status',
    (draft->>'active_seconds')::integer,
    (draft->>'total_seconds')::integer,
    (draft->>'distance_km')::double precision,
    (draft->>'avg_power_w')::integer,
    (draft->>'max_power_w')::integer,
    (draft->>'avg_cadence_rpm')::integer,
    (draft->>'avg_speed_kph')::double precision,
    (draft->>'completed_elevation_m')::double precision
  ) returning id into new_activity_id;

  for sample in select value from jsonb_array_elements(draft->'samples')
  loop
    insert into public.activity_samples (
      activity_id, timestamp_ms, elapsed_seconds, km, speed_kph, cadence_rpm,
      power_w, grade_percent, altitude_m, paused
    ) values (
      new_activity_id,
      (sample->>'timestamp_ms')::bigint,
      (sample->>'elapsed_seconds')::integer,
      (sample->>'km')::double precision,
      (sample->>'speed_kph')::double precision,
      (sample->>'cadence_rpm')::integer,
      (sample->>'power_w')::integer,
      (sample->>'grade_percent')::double precision,
      (sample->>'altitude_m')::double precision,
      (sample->>'paused')::boolean
    );
  end loop;
  return new_activity_id;
end;
$$;

create or replace function public.update_activity(target_activity_id bigint, draft jsonb)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  sample jsonb;
begin
  update public.activities set
    route_id = (draft->>'route_id')::bigint,
    started_at = (draft->>'started_at')::timestamptz,
    ended_at = (draft->>'ended_at')::timestamptz,
    status = draft->>'status',
    active_seconds = (draft->>'active_seconds')::integer,
    total_seconds = (draft->>'total_seconds')::integer,
    distance_km = (draft->>'distance_km')::double precision,
    avg_power_w = (draft->>'avg_power_w')::integer,
    max_power_w = (draft->>'max_power_w')::integer,
    avg_cadence_rpm = (draft->>'avg_cadence_rpm')::integer,
    avg_speed_kph = (draft->>'avg_speed_kph')::double precision,
    completed_elevation_m = (draft->>'completed_elevation_m')::double precision
  where id = target_activity_id and user_id = auth.uid();

  if not found then
    return false;
  end if;

  delete from public.activity_samples where activity_id = target_activity_id;
  for sample in select value from jsonb_array_elements(draft->'samples')
  loop
    insert into public.activity_samples (
      activity_id, timestamp_ms, elapsed_seconds, km, speed_kph, cadence_rpm,
      power_w, grade_percent, altitude_m, paused
    ) values (
      target_activity_id,
      (sample->>'timestamp_ms')::bigint,
      (sample->>'elapsed_seconds')::integer,
      (sample->>'km')::double precision,
      (sample->>'speed_kph')::double precision,
      (sample->>'cadence_rpm')::integer,
      (sample->>'power_w')::integer,
      (sample->>'grade_percent')::double precision,
      (sample->>'altitude_m')::double precision,
      (sample->>'paused')::boolean
    );
  end loop;
  return true;
end;
$$;

revoke all on all tables in schema public from anon;
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.create_route(jsonb) to authenticated;
grant execute on function public.update_route(bigint, jsonb) to authenticated;
grant execute on function public.duplicate_route(bigint) to authenticated;
grant execute on function public.create_activity(jsonb) to authenticated;
grant execute on function public.update_activity(bigint, jsonb) to authenticated;
